---
- name: httpd install
  become: yes
  apt:
    name: apache2

- name: monit install
  become: yes
  apt:
    name: monit
    state: present

- name: monit config
  become: yes
  template:
    src: monit.config.j2
    dest: /etc/monit/monitrc
    mode: 0700


- name: monit restart
  become: yes
  command: monit reload
