---
- name: Add nginx repository
  become: yes
  apt_repository: repo='ppa:nginx/stable'

- name: Install nginx
  become: yes
  action: apt pkg=nginx-extras state=installed update_cache=true

- name: Disable default site
  become: yes
  file: 
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart nginx
  become: yes
  shell: "service nginx restart"