# Use root/example as user/password credentials
version: '3.1'

services:

  balancer:
    image: nginx
    ports:
     - 90:90
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - web

  web:
    image: ranfert/test
    container_name: apache
    restart: always
    volumes:
      - ./web/etc/sites-enabled:/etc/apache2/sites-enabled
      - ./web/www/:/var/www/site
    links:
      - mysql57
    ports:
      - 8080:8080

  mysql57:
    image: percona:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123321
    volumes:
      - ./mysql/configs/my.cnf:/etc/mysql/conf.d/custom.cnf
      - ./mysql/mysql/:/var/lib/mysql
    ports:
      - 8081:8080

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
