---
- name: Install mysql
  become: yes
  force_apt_get: yes
  apt:
    name: 
      - mysql-server
      - mysql-client
      - python-mysqldb

- name: Change root password (fail is not a problem)
  become: yes
  mysql_user:
    name: root
    password: "{{ mysql_root_password}}"
  ignore_errors: yes